### PR TITLE
fix to pass JsonSerializerOptions to JsonSerializer

### PR DESCRIPTION
**Pull request by enikao**

### CODE REVIEW

**Comment by erk-dik** [comment]
@gragra33 are you considering to merge this PR  with main ?

**Comment by gragra33** [comment]
@enikao @erk-dik My apologies for the delay. Checked and now merged. 👍

**Comment by erk-dik** [comment]
> @enikao @erk-dik My apologies for the delay. Checked and now merged. 👍

Thank you

**Comment by erk-dik** [comment]
@gragra33 a kind reminder, would you mind updating the Nuget package? thanks

**Pull request merged**
